### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by lwl4613615** [adamhlt/ImGui-Standalone#1]
it can't follow window move

**Comment by adamhlt** [comment]
Hi, can you provide more information and maybe a screenshot/video ?
Wich mode are you using DLL or EXE ?

**Comment by lwl4613615** [comment]
When I try this project through EXE, I want to overlay this form on the form of the game, but the form of the game changes, this form does not change with the form of the game, and I draw text in the position of the overlay form (0.0), and it cannot be displayed. https://drive.google.com/file/d/1cCmuvkMM7uHfUBU-gdWO0Crao3LmXcWq/view?usp=sharing

**Comment by adamhlt** [comment]
This project is not an overlay, in EXE this is a standalone window. I am not really sure about what you are trying to do.

**Comment by lwl4613615** [comment]
Thanks, I see, this project is not an overlay form on another form, sorry to bother you

**Comment by adamhlt** [comment]
No problem I hope will find what you are looking for, else this project can be used as a DLL and have a new ImGui window into your process.
