### ISSUE TITLE
How to apply opacity to the ImGui window?

### ISSUE THREAD

**Issue by SapitoSucio** [adamhlt/ImGui-Standalone#3]
Basically title, I've tried playing with the values but I can't make it happen. 

This is what I have:

```cpp
ImGui::SetNextWindowSize(vWindowSize);
ImGui::SetNextWindowBgAlpha(0.6f); // isn't it this one?? <--
ImGui::Begin(lpWindowName, &bDraw, WindowFlags);
{
	ImGui::Text("Holi");
}
ImGui::End();
```

I went a little further and I added the WindowFlag `NoBackground`, but still appears as pure black.

![image](https://github.com/adamhlt/ImGui-Standalone/assets/7357354/161ca9b3-d7de-47ce-8bbf-e8dd9ab408aa)

Could you please enlighten me the path ?

**Comment by Chaos192** [comment]
> Thank you! This worked for me [ocornut/imgui#5988 (comment)](https://github.com/ocornut/imgui/issues/5988#issuecomment-1368490745)

Would you mind sharing the imgui fix? I tried what that comment said but it's still not rendering properly. The imgui windows are black no matter what. I am on windows 11 if that matters.
