### ISSUE TITLE
LLNK1104 CANNOT BE OPENED

### ISSUE THREAD

**Issue by NielsenDev** [adamhlt/ImGui-Standalone#5]
Had this error after installing imgui 

LNK1104 cannot open file lib d3d11.lib

**Comment by adamhlt** [comment]
Everything is explained in the README, you must install the DirectX SDK and check that it has been added to your path.

**Comment by NielsenDev** [comment]
> Everything is explained in the README, you must install the DirectX SDK and check that it has been added to your path.

oh thank you I had not looked
