### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by tylerdurdenc** [adamhlt/ImGui-Standalone#7]
Is there any "overlay" version of this? to make sure the window is always ontop and being draw in the game only?

**Comment by adamhlt** [comment]
Sorry there is no overlay at all, but I guess it will be my next project.

**Comment by adamhlt** [comment]
@tylerdurdenc the overlay version is done, you can find it here (https://github.com/adamhlt/D3D11-Overlay-ImGui)

**Comment by tylerdurdenc** [comment]
> @tylerdurdenc the overlay version is done, you can find it here (https://github.com/adamhlt/D3D11-Overlay-ImGui)

Thank you so much! github didnt notify me about your answers earlier :/

**Comment by adamhlt** [comment]
@tylerdurdenc If you are more comfortable with D3D9 here is the DirectX 9 version (https://github.com/adamhlt/D3D9-Overlay-ImGui)
