### ISSUE TITLE
WindowRounding doesn't work

### ISSUE THREAD

**Issue by thisisrandomguys** [adamhlt/ImGui-Standalone#8]
I use this project as an exe and setting the WindowRounding doesn't do anything

```
ImGuiStyle& style = ImGui::GetStyle();

    // Window Rounding
    style.WindowRounding = 8.0f;

**Comment by adamhlt** [comment]
This is problem is not concerning my project, this is about ImGui documentation.

**Comment by ConnorBP** [comment]
It is a problem concerning this project. I get this issue here, I don't on main branch imgui

**Comment by thisisrandomguys** [comment]
> This is problem is not concerning my project, this is about ImGui documentation.

This only happens on this repo. When using the stand ImGui Project the WindowRounding completly works.

**Comment by adamhlt** [comment]
Which branch of ImGui are you using ? Master or docking ?

**Comment by adamhlt** [comment]
> > This is problem is not concerning my project, this is about ImGui documentation.
> 
> 
> 
> This only happens on this repo. When using the stand ImGui Project the WindowRounding completly works.

Next time use Google, WindowRounding is disable when using viewports, so you can try to patch it yourself but it's not related to my project it's an "issue" in ImGui.

Ref: [ImGui Issue](https://github.com/ocornut/imgui/issues/6298)

**Comment by thisisrandomguys** [comment]
I use master

**Comment by adamhlt** [comment]
> I use master

This project use the docking branch. 
Next time do some research before opening an issue that was already covered on the ImGui repo
