### ISSUE TITLE
no control 

### ISSUE THREAD

**Issue by 4ksr** [adamhlt/ImGui-Standalone#9]
i'm new in imgui but i edit allthings in the menu and the issue is i can't click or close the imgui i can move the menu but i can't click to open notpad or anything

**Comment by adamhlt** [comment]
Can you provide more details about the issue, maybe share a video. I'm not sure to understand the problem.

**Comment by 4ksr** [comment]
> Can you provide more details about the issue, maybe share a video. I'm not sure to understand the problem.

i will show you video

**Comment by 4ksr** [comment]
> Can you provide more details about the issue, maybe share a video. I'm not sure to understand the problem.
look here i can't click to edit text or close the app and not all menu loaded

https://streamable.com/og1w4q

**Comment by 4ksr** [comment]
> Can you provide more details about the issue, maybe share a video. I'm not sure to understand the problem.

here the from imgui example_win32_directx11

https://streamable.com/zi4t89

**Comment by adamhlt** [comment]
I think you open the issue for the wrong project, on the first video I see you are using d3d11 overlay wich is not this repo.

**Comment by 4ksr** [comment]
> I think you open the issue for the wrong project, on the first video I see you are using d3d11 overlay wich is not this repo.

i edit all your project

**Comment by adamhlt** [comment]
> > I think you open the issue for the wrong project, on the first video I see you are using d3d11 overlay wich is not this repo.
> 
> 
> 
> i edit all your project

Yes but that's why you can't click that's because this is an overlay. So an invisible window is present all over you screen and will handle all the inputs as long as the menu is open.

**Comment by 4ksr** [comment]
> > > I think you open the issue for the wrong project, on the first video I see you are using d3d11 overlay wich is not this repo.
> > 
> > 
> > i edit all your project
> 
> Yes but that's why you can't click that's because this is an overlay. So an invisible window is present all over you screen and will handle all the inputs as long as the menu is open.

I'm new to imgui so can you help me?

**Comment by adamhlt** [comment]
This is not related to ImGui, this is about window management. I suggest you to look at ImGui Standalone (this repo) it should do want you expect. 

I will close the issue.
